/** @format */

const swaggerAutogen = require("swagger-autogen")({ openapi: "3.0.0" });
const path = require("path");

const PORT = process.env.PORT || 4000;
const swaggerGen = () => {
	const doc = {
		info: {
			version: "3.0.0",
			title: "My API",
			description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
		},
		host: `localhost:${PORT}`,
		basePath: "/",
		schemes: ["http", "https"],
		consumes: ["application/json"],
		produces: ["application/json"],
		tags: [
			{
				name: "Users",
				description: "Endpoints",
			},
		],
		components: {
			securitySchemes: {
				bearerAuth: {
					type: "http",
					scheme: "bearer",
				},
			},
			schemas: {
				bookVehicle: {
					user: {
						name: "name",
						email: "email",
						mobileNumber: "mobileNumber",
						area: "area",
						vehicleType: "vehicleType",
						acers: 0,
						dateBooked: "2024-01-01",
						startTime: 0,
						endTime: 0,
						estimatedAmount: "string",
					},
				},
				bookingUpdate: {
					driver: {
						vehicleNo: "string",
						name: "string",
						email: "string",
						number: "string",
						startTime: "string",
						endTime: "string",
						status: "string",
					},
				},
				PilotRegistration: {
					pilot: {
						Name: "John Doe",
						Gmail: "example@gmail.com",
						DOB: "1990-01-01",
						MobileNumber: "1234567890",
						VehicleNo: "ABC123",
						VehicleType: "Car",
						vehicleOwnerName: "Jane Doe",
						vehicleDriverName: "John Driver",
						Address: "123 Main St, City",
						File: "file/path",
						CreatedDate: "2022-01-01",
						regStatus: "Active",
					},
				},
				AdminRegistrationUpdate: {
					admin: {
						vehicleCompanyCode: "gerh",
						RelocationArea: "Business Area",
						RelocationAreaCode: "12345",
						CreatedDate: "2022-01-01",
						RelocationDistrict: "Business District",
						RelocationState: "Business State",
						LastUpdated: "2022-01-02",
					},
				},
			},
		},
	};

	const outputFile = "./src/output/swagger-output.json";
	const endpointsFiles = [path.join(__dirname, "../../app.js")];

	swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
		await require(path.join(__dirname, "../../app.js"));
	});
};

module.exports = swaggerGen;
